FamilyCalendar/api/urls.py
#!/usr/bin/env python3
# @author: Markus Kösters
import sys

from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path('appointment/<int:id>/', views.Appointments.appointment, name='appointment'),
    path('calendars/', views.Calendars.allCalendars, name='calendarList'),
    path('calendar/<int:year>/<int:month>/', views.Calendars.calendarPage, name='calendar'),
    path("CreateCalendar/", views.Calendars.createCalendar, name='createCalendar'),
    path('CreateAppointment/', views.Appointments.createAppointment, name='createAppointment')
]

FamilyCalendar/mainModule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('api.urls', 'api'), namespace='api')),
    # path('', include(('gui.urls', 'gui'), namespace='gui')),
]

FamilyCalendar/api/models.py
from django.db import models


class Calendar(models.Model):
    """
    Class for modeling the calendar.
    """
    year = models.IntegerField()

    def __str__(self):
        # Showing calendar-table in admin-panel with the valid year as name.
        return str(self.year)


class Month(models.Model):
    # making months a subitem of calendar
    calendar = models.ForeignKey(Calendar, on_delete=models.CASCADE)
    month = models.IntegerField()
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Day(models.Model):
    """
    Class for modeling a day inside the calendar.
    """
    month = models.ForeignKey(Month, on_delete=models.CASCADE)
    day = models.IntegerField()

    def __str__(self):
        return str(self.day)


class Appointment(models.Model):
    """
    Class defining the model of an appointment inside the Calendar.
    """
    # making appointments be a subitem of month
    month = models.ForeignKey(Day, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    date = models.DateTimeField()
    endDate = models.DateTimeField()
    persons = models.CharField(max_length=100)

    def __str__(self):
        # Showing appointments in admin-table with their name.
        return self.name

FamilyCalendar/main/templates/main/calendarTemplate.html
<!DOCTYPE html>
<html lang="en">
{% extends "main/baseTemplate.html" %}

{% block content %}
    <h1>{{list.name}}</h1>
    <ul>
    {% for appointment in list.appointment_set.all %}
        {% if appointment.complete == filter %}
            <li>{{appointment.description}}</li>
        {%  endif %}
    {% endfor %}
    </ul>
{% endblock %}

FamilyCalendar/main/templates/main/createAppointmentTemplate.html
<!DOCTYPE html>
<html lang="en">
{% extends 'main/baseTemplate.html' %}

{% block content %}
Create appointment
<form method="post" action="/CreateAppointment/">
    {% csrf_token %}
    {{form.as_ul}}
    <button type="submit" , name="save">
        Create new Appointment
    </button>
</form>
{% endblock %}

FamilyCalendar/main/templates/main/createCalendarTemplate.html
<!DOCTYPE html>
<html lang="en">
{% extends 'main/baseTemplate.html' %}

{% block content %}
Create appointment
<form method="post" action="/CreateCalendar/">
    {% csrf_token %}
    {{form.as_ul}}
    <button type="submit" , name="save">
        Create new Calendar
    </button>
</form>
{% endblock %}

FamilyCalendar/main/templates/main/homeTemplate.html
<!DOCTYPE html>
{% extends 'main/baseTemplate.html' %}
<html lang="en">
{% block content %}
    <h1>Home Page</h1>
{% endblock %}